version: 0.1

phases:
  build:
    commands:
      - echo Nothing to do yet
artifacts:
  files:
    - index.html
    - ario_tamaddoni_resume.pdf
    - styles/main.css
    - images/*
    - favicon.ico
